### ISSUE TITLE
macstadium_aws_vpn module isn't publicly available on web

### ISSUE THREAD

**Issue by laser** [consultantRR/macstadium-aws-vpn#1]
Hello!

The sources of the [module that you're using in your Terraform config-files](https://github.com/ProbablyRusty/macstadium-aws-vpn/blob/master/main.tf#L12) aren't publicly available on the web (which makes your config files a little hard to use ;)

Do you control those files? If so, would you make them public?

Take care,

Erin

**Comment by ProbablyRusty** [comment]
Hi @laser, thanks for letting me know about this. I do control those files, and they were in fact open, but the URLs in this repo were pointing to the wrong place. Fixed in #2.

**Comment by laser** [comment]
Thanks a bunch!
